research_task:
  description: >
    Write and execute code to gather information on USTA tournaments from the website 
    {website}. Search by category {category}, section {section}, and district {district} 
    and date period between {today} and {three_months_from_now}. Include only tournaments that 
    are open for registration. Collect the following information for each tournament:
    - Name
    - Dates
    - Location
    - Registration link
    - Category
    - Section
    - District
    - Number of players registered for {level} Women's Singles
    - Number of players registered for {level} Women's Doubles
    - Number of players registered for {level} Mixed Doubles
    - Price for {level} Women's Singles
    - Price for {level} Women's Doubles
    - Price for {level} Mixed Doubles
  expected_output: >
    A list of dictionaries, each containing the information for a tournament.
  agent: researcher

data_visualization_task:
  description: >
    Generate a map visualization of USTA tournaments based on the data provided by the researcher.
    The map should show the locations of the tournaments, with markers indicating the number of players registered
    for each tournament. The map should be interactive and allow users to zoom in and out. Hovering
    over an event should display the tournament
    - Name
    - Dates
    - Location
    - Distance from {home_city}
    - Registration link
    - Number of players registered for {level} Women's Singles
    - Number of players registered for {level} Women's Doubles
    - Number of players registered for {level} Mixed Doubles
    - Price for {level} Women's Singles
    - Price for {level} Women's Doubles
    - Price for {level} Mixed Doubles
    The user should be able to filter the tournaments by the distance from {home_city} and the 
    number of players registered for each event.
  expected_output: >
    An HTML file with an interactive map visualization of USTA tournaments with the specified features.
  agent: data_visualization_specialist
