---
get_usta_data_task:
    description: >
        Run the main.py script in the src/data_retrieval directory within the https://github.com/mvdemko/data-retrieval repository.
    expected_output: >
        The output of the script, including any results or error messages.
    agent: python_code_runner

data_visualization_task:
    description: >
        Generate a map visualization of USTA tournaments based on the data provided by the python code runner.
        The map should show the locations of the tournaments. The map should be interactive and allow users to zoom in and out. Hovering
        over an event should display the tournament
        - Name
        - Dates
        - Location
        - Distance from {home_city}
        - Registration link
        - Number of players registered for {level} Women's Singles
        - Number of players registered for {level} Women's Doubles
        - Number of players registered for {level} Mixed Doubles
        The user should be able to filter the tournaments by the distance from {home_city} and the  number of players registered for each event.
    expected_output: >
        A output/maps.html file with an interactive map visualization of USTA tournaments with the specified features.
    agent: data_visualization_specialist
